def run_generated_code(code: str, context: dict):
    """
    Executes generated Python code with access to limited variables in `context`.
    Captures a variable named `result` from the code.

    Parameters:
        code (str): The Python code to execute (usually generated by OpenAI).
        context (dict): Dictionary of objects (like stubs) to inject.

    Returns:
        The value of `result` if successful, or an error message.
    """
    local_vars = {}

    try:
        exec(code, context, local_vars)
        return local_vars.get("result", "?? No 'result' variable returned by code.")
    except Exception as e:
        return f"? Execution error: {e}"
